# Lambda official base
FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

# Install dependencies with mirror
COPY requirements.lambda.txt .
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.lambda.txt

# Copy app code
COPY app/ ./app/

# Lambda handler
CMD ["app.main.handler"]
